In [33]:
import pandas as pd

In [34]:
nutrition = pd.read_excel(r'C:\Users\Osas\Personal_projects\PCOS_project\nutritionalsamples.xlsx')

In [35]:
nutrition

,food,protein(g),carbs(g),fiber(g),fats(g),sugar(g),kcal,gi
0,almonds,21.40,20.00,10.80,51.10,3.90,584,15
1,rolled oats,13.50,68.70,10.40,5.89,1.00,379,55
2,bread,14.30,72.80,2.70,1.65,5.00,372,90
3,gold potatoes,1.81,16.00,13.80,0.26,0.65,72,58
4,sweet potatoes,1.58,17.30,4.44,0.38,6.06,77,70
5,chicken breast,22.50,0.00,0.00,1.93,0.00,112,0
6,greek yogurt,9.00,3.98,0.00,5.00,4.00,97,11
7,peanut butter,24.00,22.70,6.30,49.40,9.00,589,25
8,chia seeds,17.00,38.30,34.00,31.00,0.00,490,30
9,bacon,40.90,2.10,0.00,36.50,3.14,512,0
10,broccoli,2.57,6.27,2.40,0.34,1.40,32,15
11,eggs,12.40,0.96,0.75,9.96,0.20,147,0
12,lentils,23.60,62.20,31.00,1.92,1.80,351,30
13,avocados,1.81,8.32,6.70,20.30,0.70,206,10
14,apples,0.27,14.10,2.50,0.14,10.60,53,36
15,brown rice,7.25,76.70,3.00,3.31,0.40,368,50
16,white rice,7.04,80.30,0.10,1.03,0.10,370,70
17,cottage cheese,11.00,4.31,0.00,2.30,4.10,84,30
18,american cheese,17.50,6.35,0.00,31.10,3.76,373,0
19,blueberries,0.70,14.60,5.00,0.31,9.36,57,53

In [36]:
nutrition['net carbs'] = nutrition['carbs(g)'] - nutrition['fiber(g)']

In [42]:
foods = pd.read_csv(r'C:\Users\Osas\Personal_projects\PCOS_project\foods.csv')

In [43]:
foods.head()

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category
0,Cows' milk,1 qt.,976,660,32,40,36.0,0.0,48.0,Dairy products
1,Milk skim,1 qt.,984,360,36,0,0.0,0.0,52.0,Dairy products
2,Buttermilk,1 cup,246,127,9,5,4.0,0.0,13.0,Dairy products
3,"Evaporated, undiluted",1 cup,252,345,16,20,18.0,0.0,24.0,Dairy products
4,Fortified milk,6 cups,"1,419","1,373",89,42,23.0,1.4,119.0,Dairy products

"t" in nutrient columns represents that only a trace amount is available.

In [44]:
def score(row):
    protein_weight = 2
    fat_weight = -3
    fiber_weight = 2
    carb_weight = -1.5

    calc_score = (protein_weight * row['protein(g)'] + fat_weight * row['sugar(g)'] + fiber_weight * row['fiber(g)'] + carb_weight * row['carbs(g)'])
    return calc_score

In [45]:
nutrition['PCOS_score'] = nutrition.apply(score, axis=1)

In [46]:
nutrition.head()

,food,protein(g),carbs(g),fiber(g),fats(g),sugar(g),kcal,gi,net carbs,PCOS_score
0,almonds,21.40,20.0,10.80,51.10,3.90,584,15,9.20,22.70
1,rolled oats,13.50,68.7,10.40,5.89,1.00,379,55,58.30,-58.25
2,bread,14.30,72.8,2.70,1.65,5.00,372,90,70.10,-90.20
3,gold potatoes,1.81,16.0,13.80,0.26,0.65,72,58,2.20,5.27
4,sweet potatoes,1.58,17.3,4.44,0.38,6.06,77,70,12.86,-32.09

In [48]:
def pcos_score(row):
    protein_weight = 2
    fat_weight = -3
    fiber_weight = 2
    carb_weight = -1.5

    calc_score = (protein_weight * row['Protein'] + fat_weight * row['Sat.Fat'] + fiber_weight * row['Fiber'] + carb_weight * row['Carbs'])
    return calc_score

In [49]:
foods['PCOS_score'] = foods.apply(pcos_score, axis=1)

In [50]:
foods.head()

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category,PCOS_score
0,Cows' milk,1 qt.,976,660,32,40,36.0,0.0,48.0,Dairy products,-116.0
1,Milk skim,1 qt.,984,360,36,0,0.0,0.0,52.0,Dairy products,-6.0
2,Buttermilk,1 cup,246,127,9,5,4.0,0.0,13.0,Dairy products,-13.5
3,"Evaporated, undiluted",1 cup,252,345,16,20,18.0,0.0,24.0,Dairy products,-58.0
4,Fortified milk,6 cups,"1,419","1,373",89,42,23.0,1.4,119.0,Dairy products,-66.7

In [51]:
foods

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category,PCOS_score
0,Cows' milk,1 qt.,976,660,32,40,36.0,0.0,48.0,Dairy products,-116.0
1,Milk skim,1 qt.,984,360,36,0,0.0,0.0,52.0,Dairy products,-6.0
2,Buttermilk,1 cup,246,127,9,5,4.0,0.0,13.0,Dairy products,-13.5
3,"Evaporated, undiluted",1 cup,252,345,16,20,18.0,0.0,24.0,Dairy products,-58.0
4,Fortified milk,6 cups,"1,419","1,373",89,42,23.0,1.4,119.0,Dairy products,-66.7
...,...,...,...,...,...,...,...,...,...,...,...
330,Fruit-flavored soda,12 oz.,346,161,0,0,0.0,0.0,42.0,"Drinks,Alcohol, Beverages",-63.0
331,Ginger ale,12 oz.,346,105,0,0,0.0,0.0,28.0,"Drinks,Alcohol, Beverages",-42.0
332,Root beer,12 oz.,346,140,0,0,0.0,0.0,35.0,"Drinks,Alcohol, Beverages",-52.5
333,Coffee,1 cup,230,3,0,0,0.0,0.0,1.0,"Drinks,Alcohol, Beverages",-1.5
334,Tea,1 cup,230,4,0,0,0.0,0.0,1.0,"Drinks,Alcohol, Beverages",-1.5

In [58]:
def recommend(df, top=10, category=None):
    filtered = df.copy()

    if category:
        filtered = filtered[filtered['Category'] == category]

    recommendation = filtered.sort_values(by='PCOS_score', ascending=False)
    return recommendation.head(top)

In [67]:
recommendations = recommend(foods, 10, "Fruits A-F")

In [68]:
recommendations

,Food,Measure,Grams,Calories,Protein,Fat,Sat.Fat,Fiber,Carbs,Category,PCOS_score
161,"Watercress stems, raw",1 cup,50,9,1,0,0.0,0.3,1.0,Fruits A-F,1.1
163,Apple vinegar,1/3 cup,100,14,0,0,0.0,0.0,3.0,Fruits A-F,-4.5
174,Cantaloupe,1/2 med.,380,40,1,0,0.0,2.2,9.0,Fruits A-F,-7.1
172,Blackberries,1 cup,144,85,2,1,0.0,6.6,19.0,Fruits A-F,-11.3
168,Fresh,3 med.,114,55,1,0,0.0,0.7,14.0,Fruits A-F,-17.6
176,"Fresh, raw",1 cup,114,65,1,0,0.0,0.8,15.0,Fruits A-F,-18.9
164,"Apples, raw",1 med,130,70,0,0,0.0,1.0,18.0,Fruits A-F,-25.0
180,"Fresh, raw figs",3 med.,114,90,2,0,0.0,1.0,22.0,Fruits A-F,-27.0
171,Banana,1 med.,150,85,1,0,0.0,0.9,23.0,Fruits A-F,-30.7
175,Cherries,1 cup,257,100,2,1,0.0,2.0,26.0,Fruits A-F,-31.0

In [70]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

# Pick relevant features
features = foods[['Protein', 'Fat', 'Sat.Fat', 'Fiber', 'Carbs', 'PCOS_score']]

In [71]:
print(features.isnull().sum())

Protein       0
Fat           0
Sat.Fat       1
Fiber         0
Carbs         0
PCOS_score    1
dtype: int64

In [72]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# Select features for similarity
features = foods[['Protein', 'Fat', 'Sat.Fat', 'Fiber', 'Carbs', 'PCOS_score']]

# Handle missing values
features = features.fillna(features.mean())

# Scale
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# Cosine similarity
sim_matrix = cosine_similarity(features_scaled)

In [86]:
def recommend_similar(food_name, top_n=5):
    if food_name not in foods['Food'].values:
        return f"⚠️ '{food_name}' not found in dataset. Try one of: {foods['Food'].sample(5).tolist()}"
    
    idx = foods[foods['Food'] == food_name].index[0]
    sim_scores = list(enumerate(sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    top_indices = [i for i, _ in sim_scores[1:top_n+1]]
    print(idx)
    return foods.iloc[top_indices][['Food', 'Category', 'PCOS_score']]

# Example
rec = recommend_similar("Shrimp", top_n=5)

88

In [87]:
rec

                      Food        Category  PCOS_score
11              skim. milk  Dairy products         9.5
80                 Lobster   Fish, Seafood        36.0
73                     Cod   Fish, Seafood        56.0
83             Oyster stew   Fish, Seafood        35.0
52  Corned beef hash Dried   Meat, Poultry        26.0